# 4장 예외
## 4.1 사라진 SQLException
```
public void deleteAll() throws SQLException {
    this.jdbcContext.executeSql("delete from users");
}
```
**JdbcTemplate 적용 전**
<br/><br/>

```
public void deleteAll() {
    this.jdbcTemplate.update("delete from users");
}
```
**JdbcTemplate 적용 후**
<br/><br/>

- JdbcTemplate 적용 전에는 있었던 throws SQLException이 선언이 적용 후에는 사라졌다.
- SQLException은 JDBC API의 메소드들이 던지는 것이므로 당연히 있어야 한다.
- 비록 로그를 남기기 위해 catch를 했다고 해도 다시 JDBC 템플릿 메소드 밖으로 던져서 예외상황이 발생했다는 사실을 알려야 한다.
- 이 SQLException은 어디로 사라진 것일까?
<br/>



### 4.1.1 초난감 예외처리

### 예외 블랙홀
<br/>

```
try {
    ...
} catch(SQLException e) {
}
```
**초난감 예외처리 코드 1**
<br/><br/>

- JDBC API를 썼더니 IDE가 친절하게도 빨간 줄을 그어주며 '처리되지 않은 예외가 있다'라고 에러 표시를 해준다. 이를 보고 자바 언어 기초 시간에 배운 대로 try/catch 블록을 둘러싸주는 것으로 해결한다. 컴파일러 에러 메시지도 없어지고 간단한 예제에서라면 별문제 없이 잘 동작한다.
- 위의 예시 코드 또한 예외를 잡고는 아무것도 하지 않는다. 예외 발생을 무시해버리고 정상적인 상황인 것처럼 다음 라인으로 넘어가겠다는 분명한 의도가 있는 게 아니라면 `연습 중에도 절대 만들어서는 안되는 코드다.`
<br/>

- 예외가 발생하면 그것을 catch 블록을 써서 잡아내는 것까지는 좋은데 아무것도 하지 않고 별문제 없는 것처럼 넘어가 버리는 건 원치 않는 예외가 발생하는 것보다도 훨씬 더 나쁜 일이다.
- 왜냐하면 프로그램 실행 중에 `어디선가 오류가 있어서 예외가 발생했는데 그것을 무시하고 계속 진행해버리기 때문`이다.
- 결국 발생한 예외로 인해 어떤 기능이 비정상적으로 동작하거나, 메모리가 리소스가 소진되거나, 예상치 못한 다른 문제를 일으킬 것이다.
- 최종적으로 오작동을 하거나 시스템 오류가 나서 운영자가 알아차렸을 때는 이미 조치를 취하기엔 너무 늦었다.
- 더 큰 문제는 그 시스템 오류나 이상한 결과의 원인이 무엇인지 찾아내기가 매우 힘들다는 것이다.
<br/>

```
} catch(SQLException e) {
    System.out.println(e);
}
```
**초난감 예외처리 코드 2**
<br/><br/>

```
} catch(SQLException e) {
    e.printStackTrace();
}
```
**초난감 예외처리 코드 3**
<br/><br/>

***예외가 발생하면 화면에 출력해주는데 뭐가 문제일까?***

- 개발 중에는 IDE 콘솔이나 서버 실행창에 이 메시지가 눈에 띄게 보이므로 문제가 생겨도 금방 알아차리고 뭔가 조치를 취할 수 있다.
- 하지만 다른 로그나 메시지에 금방 묻혀버리면 놓치기 쉽상이며, 운영 서버에서는 콘솔 로그를 누군가가 계속 모니터링하지 않는 한 예외 코드는 심각한 폭탄으로 남게 된다.
- `예외는 반드시 처리되어야 한다.`
<br/>

- 예외를 처리할 때 반드시 지켜야 할 핵심 원칙은 `모든 예외는 적절하게 복구되든지 아니면 작업을 중단시키고 운영자 또는 개발자에게 분명하게 통보되어야 한다.`
- SQLException이 발생하는 이유는 SQL에 문법 에러가 있거나 DB에서 처리할 수 없을 정도로 데이터 액세스 로직에 심각한 버그가 있거나, 서버가 죽거나 네트워크가 끊기는 등의 심각한 상황이 벌어졌기 때문이다.
- 그런데 그냥 예외를 무시하고 정상적으로 동작하고 있는 것처럼 모른 척 다음 코드로 실행을 이어간다는 건 말이 되지 않는다. 콘솔이나 로그에 예외 메시지를 출력만 하고 끝내는 것은 아무런 도움이 되지 않는다.
<br/>

```
} catch(SQLException e) {
    e.printStackTrace();
    System.exit(1);
}
```
**그나마 나은 예외처리**
<br/><br/>

- 위의 예시가 모범적인 것은 아니지만, 예외를 무시하거나 잡아먹어 버리는 코드는 만들지 말라는 뜻이다.
- 굳이 예외를 잡아서 뭔가 조치를 취할 방법이 없다면 잡지 말아야 한다.
- 메소드에 throws SQLException을 선언해서 메소드 밖으로 던지고 자신을 호출한 코드에 예외처리 책임을 전가해버리자.
<br/>


### 무의미하고 무책임한 throws
- catch 블록으로 예외를 잡아봐야 해결할 방법도 없고 JDK API나 라이브러리가 던지는 각종 이름도 긴 예외들을 처리하는 코드를 매번 throws로 선언하기 귀찮아지기 시작하면, 아래와 같이 throws Exception을 메소드 선언에 기계적으로 붙이는 개발자도 있다.
<br/>

```
public void method1() throws Exception {
    method2();
    ...
}

public void method2() throws Exception {
    method3();
    ...
}

public void method3() throws Exception {
    ...
}
```
**초난감 예외처리 4**
<br/><br/>

- EJB(!!)가 한창 쓰이던 시절에 흔히 볼 수 있던 코드다.
- throws Exception을 이용해 모든 예외를 무조건 던져버리는 선언을 모든 메소드에 기계적으로 넣는 것이다.
- 사용하려는 메소드에 throws Exception이 선언되어 있으면, 그런 메소드 선언에서는 의미 있는 정보를 얻을 수 없다. 정말 무엇인가 실행 중에 예외적인 상황이 발생할 수 있다는 것인지, 아니면 습관적으로 복사해서 붙여넣은 것은지 알 수가 없다. 결국 이런 메소드를 사용하는 메소드에서도 throws Exception을 따라서 붙이는 수밖에 없다.
<br/>



### 4.1.2 예외의 종류와 특징
- 예외를 어떻게 다뤄야 할까? 가장 큰 이슈는 **체크 예외 checked exception**라고 불리는 명시적인 처리가 필요한 예외를 사용하고 다루는 방법이다.
- Java에서 throw를 통해 발생시킬 수 있는 예외는 크게 3가지가 있다.
<br/>

#### Error
- 첫번째는 java.lang.Error 클래스의 서브클래스들이다.
- 에러는 시스템에 뭔가 비정상적인 상황이 발생했을 경우에 사용된다.
- 그래서 주로 Java VM에서 발생시키는 것이고 애플리케이션 코드에서 잡으려고 하면 안 된다.
- OOM(OutOfMemoryError)나 ThreadDeath 같은 에러는 catch 블록으로 잡아봤자 아무런 대응 방법이 없기 때문이다.
- 따라서 시스템 레벨에서 특별한 작업을 하는 게 아니라면 애플리케이션에서는 이런 에러에 대한 처리는 신경 쓰지 않아도 된다. (사전에 방지할 수 있는 문제는 코드로 막는게 좋지 않...나?)
<br/>

#### Exception과 체크 예외
- java.lang.Exception 클래스와 그 서브클래스로 정의되는 예외들은 에러와 달리 개발자들이 만든 애플리케이션 코드의 작업 중에 예외상황이 발생했을 경우에 사용된다.
- Exception 클래스는 다시 체크 예외와 **언체크 예외 unchecked exception**으로 구분된다. 전자는 Exception 클래스의 서브클래스이면서 RuntimeException 클래스를 상속하지 않은 것들이고, 후자는 RuntimeException을 상속한 클래스들을 말한다.
- RuntimeException은 Exception의 서브클래스이므로 Exception의 일종이긴 하지만 Java는 이 RuntimeException과 그 서브클래스는 특별하게 다룬다.
<br/>

![Exception의 두 가지 종류](https://github.com/taechacode/TIL/assets/63395751/70343f33-58ae-49e2-93f2-800a187e6e0c)
**Exception의 두 가지 종류**
<br/>

- 일반적으로 예외라고 하면 Exception 클래스의 서브클래스 중에서 RuntimeException을 상속하지 않은 것만을 말하는 체크 예외라고 생각해도 된다.
- 체크 예외가 발생할 수 있는 메소드를 사용할 경우 반드시 예외를 처리하는 코드를 함께 작성해야 한다.
- 사용할 메소드가 체크 예외를 던진다면 이를 catch 문으로 잡든지, 아니면 다시 throws를 정의해서 메소드 밖으로 던져야 한다. 그렇지 않으면 컴파일 에러가 발생한다.
- Java 언어와 JDK의 초기 설계자들은 체크 예외를 발생 가능한 예외에 모두 적용하려고 했던 것 같다. 그래서 IOException이나 SQLException을 비롯해서 예외적인 상황에서 던져질 가능성이 있는 것들 대부분이 체크 예외로 만들어져 있다.
<br/>

#### RuntimeException과 언체크/런타임 예외
- java.lang.RuntimeException 클래스를 상속한 예외들은 명시적인 예외처리를 강제하지 않기 때문에 언체크 예외라고 불린다. 또는 대표 클래스 이름을 따서 런타임 예외라고도 한다.
- 에러와 마찬가지로 런타임 예외는 catch 문으로 잡거나 throws로 선언하지 않아도 된다. (명시적으로 잡아도 상관은 없다)
- `런타임 예외는 주로 프로그램의 오류가 있을 때 발생하도록 의도된 것들`이다. 대표적으로 오브젝트를 할당하지 않은 레퍼런스 변수를 사용하려고 시도했을 때 발생하는 **NullPointerException**이나, 허용되지 않는 값을 사용해서 메소드를 호출할 때 발생하는 **IllegalArgumentException** 등이 있다. 이런 예외는 코드에서 미리 조건을 체크하도록 주의 깊게 만든다면 피할 수 있다.
- 피할 수 있지만 개발자가 부주의해서 발생할 수 있는 경우에 발생하도록 만든 것이 런타임 예외다. 따라서 런타임 예외는 예상하지 못했던 예외상황에서 발생하는 게 아니기 대문에 굳이 catch나 throws를 사용하지 않아도 되도록 만든 것이다.
<br/>

- 그런데 Java 언어를 설계하고 JDK를 개발한 사람들의 이런 설계의도는 현실과 잘 맞지 않았고 비난의 대상이 되기도 했다. 특히 체크 예외의 불필요성을 주장하는 사람들이 늘어났다.
- 체크 예외가 예외처리를 강제하는 것 때문에 예외 블랙홀이나 무책임한 throws 같은 코드가 남발됐다.
- 최근에 새로 등장하는 Java 표준 스펙의 API들은 예상 가능한 예외상황을 다루는 예외를 체크 예외로 만들지 않는 경향이 있기도 하다.
<br/>



### 4.1.3 예외처리 방법
#### 예외 복구
- 첫 번째 예외처리 방법은 `예외상황을 파악하고 문제를 해결해서 정상 상태로 돌려놓는 것이다.`
- 네트워크가 불안해서 가끔 서버에 접속이 잘 안 되는 열악한 환경에 있는 시스템이라면 원격 DB 서버에 접속하다 실패해서 SQLException이 발생할 수도 있다. 이럴 경우에 일정 시간 대기했다가 다시 접속을 시도해보는 방법을 사용해서 예외상황으로부터 복구를 시도할 수 있다.
- 예외처리 코드를 강제하는 체크 예외들은 이렇게 예외를 어떤 식으로든 복구할 가능성이 있는 경우에 사용한다.
- 밑의 예시는 통제 불가능한 외부 요인으로 인해 예외가 발생하면 MAX_RETRY만큼 재시도를 하는 간단한 예이다. 사전에 미리 성공 여부를 확인할 수 없고, 재시도가 의미있는 경우라면 이렇게 최대 횟수만큼 반복적으로 시도함으로써 예외상황에서 복구되게 할 수 있다.
<br/>

```
int maxretry = MAX_RETRY;
while(maxretry -- > 0) {
    try {
        ...
        return;
    }
    catch(SomeException e) {
        // 로그 출력. 정해진 시간만큼 대기
    }
    finally {
        // 리소스 반납. 정리 작업
    }
}
throw new RetryFailedException(); // 최대 재시도 횟수를 넘기면 직접 예외 발생
```
**재시도를 통해 예외를 복구하는 코드**
<br/>

#### 예외처리 회피
- 두 번째 방법은 `예외처리를 자신이 담당하지 않고 자신을 호출한 쪽으로 던져버리는 것이다.` throws 문으로 선언해서 예외가 발생하면 알아서 던져지게 하거나 catch문으로 일단 예외를 잡은 후에 로그를 남기고 다시 예외를 던지는 것이다.
- 텅 비어있는 catch 블록으로 잡아서 예외가 발생하지 않은 것처럼 만드는 경우는, 드물지만 특별한 의도를 가지고 예외를 복구했거나 아무 개념이 없어서 그런 것이지 회피한 것은 아니다.
- 예외처리를 회피하려면 반드시 다른 오브젝트나 메소드가 예외를 대신 처리할 수 있도록 아래의 예시처럼 던져줘야 한다.
<br/>

```
public void add() throws SQLException {
    // JDBC API
}
```
**예외처리 회피1**
<br/>

```
public void add() throws SQLException {
    try {
        // JDBC API
    }
    catch(SQLException e) {
        // 로그 출력
        throw e;
    }
}
```
**예외처리 회피2**
<br/>

- 예외를 회피하는 것은 예외를 복구하는 것처럼 의도가 분명해야 한다.
<br/>

#### 예외 전환
- 마지막으로 예외를 처리하는 방법은 `예외 전환 exception translation`을 하는 것이다. 예외 회피와 비슷하게 예외를 복구해서 정상적인 상태로는 만들 수 없기 때문에 예외를 메소드 밖으로 던지는 것이다.
- 하지만 예외 회피와 달리, 발생한 예외를 그대로 넘기는 게 아니라 `적절한 예외로 전환해서 던진다는 특징이 있다.`
<br/>

- 예외 전환은 보통 두 가지 목적으로 사용된다.
- 첫째는 내부에서 발생한 예외를 그대로 던지는 것이 그 예외상황에 대한 적절한 의미를 부여해주지 못하는 경우에, 의미를 분명하게 해줄 수 있는 예외로 바꿔주기 위해서다.
    - 예를 들어 새로운 사용자를 등록하려고 시도했을 때 아이디가 같은 사용자가 있어 DB 에러가 발생하면 JDBC API는 SQLException을 발생시킨다.
    - 이 경우 DAO 메소드가 SQLException을 그대로 밖으로 던져버리면, DAO를 이용해 사용자를 추가하려고 한 서비스 계층 등에서는 왜 SQLException이 발생했는지 쉽게 알 방법이 없다.
    - 이럴 때는 DAO에서 SQLException의 정보를 해석해서 DuplicateUserIdException 같은 예외로 바꿔서 던져주는게 좋다.
    - 의미가 분명한 예외가 던져지면 서비스 계층 오브젝트에는 적절한 복구 작업을 시도할 수 있다.
<br/>

```
public void add(User user) throws DuplicateUserIdException, SQLException {
	try {
		// JDBC를 이용해 user 정보를 DB에 추가하는 코드 또는
		// 그런 기능을 가진 다른 SQLException을 던지는 메소드를 호출하는 코드
	}
	catch(SQLException e) {
		// ErrorCode가 MySQL의 "Duplicate Entry(1062)"이면 예외 전환
		if(e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
			throw DuplicateUserIdException();
		else
			throw e; // 그 외의 경우는 SQLException 그대로
	}
}
```
**사용자 정보 등록 시 중복된 아이디 값이 발생할 경우 의미 있는 DuplicateKeyException으로 전환해주는 DAO 메소드**
<br/>

- 두 번째 전환 방법은 `예외를 처리하기 쉽고 단순하게 만들기 위해 포장wrap하는 것이다.`
    - 중첩 예외를 이용해 새로운 예외를 만들고 원인cause이 되는 예외를 내부에 담아서 던지는 방식은 같다. 하지만 의미를 명확하게 하려고 다른 예외로 전환하는 것이 아니다. 주로 `예외처리를 강제하는 체크 예외를 언체크 예외인 런타임 예외로 바꾸는 경우에 사용한다.`
    - 대표적인 예시로 EJBException이 있다. EJB 컴포넌트 코드에서 발생하는 대부분의 체크 예외는 비즈니스 로직으로 볼 때 의미 있는 예외이거나 복구 가능한 예외가 아니다. 이런 경우에는 런타임 예외인 EJBException으로 포장해서 던지는 편이 낫다.
    - EJBException은 RuntimeException 클래스를 상속한 런타임 예외이기 때문에 EJB는 이를 시스템 Exception으로 인식하고 트랜잭션을 자동으로 롤백해준다. (일일이 예외를 잡아봐야 복구할만한 방법이 없기 때문에..)
    - 반대로 애플리케이션 로직 상에서 예외조건이 발견되거나 예외상황이 발생할 수도 있다. 이런 것은 API가 던지는 예외가 아니라 애플리케이션 코드에서 의도적으로 던지는 예외다. 이때는 체크 예외를 사용하는 것이 적절하다. 비즈니스 적인 의미가 있는 예외는 이에 대한 적절한 대응이나 복구 작업이 필요하기 때문이다.
<br/>

```
	try {
		OrderHome orderHome = EJBHomeFactory.getInstance().getOrderHome();
		Order order = orderHome.findByPrimaryKey(Integer id);
	} catch (NamingException ne) {
		throw new EJBException(ne);
	} catch (SQLException se) {
		throw new EJBException(se);
	} catch (RemoteException re) {
		throw new EJBException(re);
	}
```
**예외 포장**
<br/><br/>



### 4.1.4 예외처리 전략
#### 런타임 예외의 보편화
- 자바가 처음 만들어질 때 많이 사용되었던 애플릿이나 AWT, 스윙Swing을 사용한 독립형 애플리케이션에서는 통제 불가능한 시스템 예외라도 애플리케이션의 작업이 중단되지 않게 해주고 상황을 복구해야 했다. 예를 들어 워드의 파일 열기 기능에서 사용자가 입력한 이름에 해당하는 파일을 찾을 수 없다고 애플리케이션이 종료돼버리게 할 수는 없다.
- 하지만 자바 엔터프라이즈 서버 환경은 다르다. 수많은 사용자가 동시에 요청을 보내고 각 요청이 독립적인 작업으로 취급된다. 독립형 애플리케이션과 달리 서버의 특정 계층에서 예외가 발생했을 때 작업을 일시 중지하고 사용자와 바로 커뮤니테이션하면서 예외상황을 복구할 수 있는 방법이 없다.
- 차라리 애플리케이션 차원에서 예외상황을 미리 파악하고, 예외가 발생하지 않도록 차단하는 게 좋다. 또는 프로그램의 오류나 외부 환경으로 인해 예외가 발생하는 경우라면 빨리 해당 요청의 작업을 취소하고 서버 관리자나 개발자에게 통보해주는 편이 낫다.
<br/>

#### add() 메소드의 예외처리
- DuplicateUserIdException을 RuntimeException을 상속한 런타임 예외로 만든다. 그리고 SQLException이 발생한 경우에는 DuplicateUserIdException을 던지게 하여 예외 전환을 사용한다.
- 이제 이 add() 메소드를 사용하는 오브젝트는 SQLException을 처리하기 위해 불필요한 throws 선언을 할 필요는 없으면서, 필요한 경우 아이디 중복 상황을 처리하기 위해 DuplicatedUserIdException을 이용할 수 있다.
<br/>

#### 애플리케이션 예외
- 시스템 또는 외부의 예외상화잉 원인이 아니라 애플리케이션 자체의 로직에 의해 의도적으로 발생시키고, 반드시 catch해서 무엇인가 조치를 취하도록 요구하는 예외도 있다. 이런 예외들을 일반적으로 `애플리케이션 예외`라고 한다.
- 예를 들어 사용자가 요청한 금액을 은행계좌에서 출금하는 기능을 가진 메소드가 있다고 생각해보자. 현재 잔고를 확인하고, 허용하는 범위를 넘어서 출금을 요청하면 출금 작업을 중단시키고 적절한 경고를 사용자에게 보내야 한다.
    - 첫 번째 메소드 설계 방법은 정상적인 출금처리를 했을 경우와 잔고 부족이 발생했을 경우에 각각 다른 종류의 return 값을 돌려주는 것이다.
    - 두 번째 방법은 정상적인 흐름을 따르는 코드는 그대로 두고, 잔고 부족과 같은 예외 상황에서는 비즈니스적인 의미를 띤 예외(체크 예외)를 던지도록 만드는 것이다.
<br/>

### 4.1.5 SQLException은 어떻게 됐나?
- 지금까지 다룬 예외처리에 대한 내용은 JdbcTemplate을 적용하는 중에 throws Exception 선언이 왜 사라졌는가를 설명하는 데 필요한 것이었다.
- 대부분의 SQLException은 코드 레벨에서는 복구할 방법이 없다.
- 따라서 에외처리 전략을 사용해야 한다. 필요도 없는 기계적인 throws 선언이 등장하도록 방치하지 말고 가능한 빨리 언체크/런타임 예외로 전환해줘야 한다.
- 스프링 JdbcTemplate은 템플릿과 콜백 안에서 발생하는 모든 SQLException을 런타임 예외인 DataAccessException으로 포장해서 던져준다. 따라서 JdbcTemplate을 사용하는 UserDao 메소드에선 꼭 필요한 경우에만 런타임 예외인 DataAccessException을 잡아서 처리하면 되고 그 외의 경우에는 무시해도 된다. 그래서 DAO 메소드에서 SQLException이 모두 사라졌다.
<br/>

## 4.2 예외 전환

### 4.2.1 JDBC의 한계

#### 비표준 SQL
#### 호환성 없는 SQLException의 DB 에러정보
<br/>

### 4.2.2 DB 에러 코드 매핑을 통한 전환
<br/>

### 4.2.3 DAO 인터페이스와 DataAccessException 계층구조

#### 데이터 액세스 예외 추상화와 DataAccessException 계층구조
<br/>

### 4.2.4 기술에 독립적인 UserDao 만들기
#### 인터페이스 적용
#### 테스트 보완
#### DataAccessException 활용 시 주의사항
